language: python
python:
  - "3.6"

before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install g++-4.9

install:
  - pip install .
  - pip install -r requirements.txt

script:
  - py.test --cov=./ --cov-config=.coveragerc

after_success:
  - coveralls
