dist: xenial

language: python

python:
  - "3.7"

before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install g++-4.9

install:
  - CC=gcc-4.9 CXX=g++-4.9 python setup.py build_ext
  - pip install .[C]
  - pip install -r requirements.txt

script:
  - py.test --cov=./ --cov-config=.coveragerc

after_success:
  - coveralls
