dist: bionic

language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
  - sudo sh -c "echo 'deb [ arch=amd64 ] https://downloads.skewed.de/apt bionic main' >> /etc/apt/sources.list"
 # - sudo sh -c "echo 'deb-src [trusted=yes] http://downloads.skewed.de/apt/bionic xenial universe' >> /etc/apt/sources.list"
  - sudo apt-key adv --keyserver keys.openpgp.org --recv-key 612DEFB798507F25
  #- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
 # - sudo apt-get install g++-4.9
  - sudo apt-get install python3-graph-tool
  - sudo apt-get install libgmp3-dev
  - wget http://www.mpfr.org/mpfr-4.0.1/mpfr-4.0.1.tar.bz2
  - tar jxvf mpfr-4.0.1.tar.bz2
  - cd mpfr-4.0.1/
  - ./configure
  - make && make check && make install
  - wget https://mirrors.sjtug.sjtu.edu.cn/gnu/mpc/mpc-1.1.0.tar.gz
  - tar zxvf tpc-1.1.0.tar.gz
  - cd mpc-1.1.0/
  - ./configure
  - make && make check && make install
  - sudo apt-get install -y python3-gmpy2


install:
  - CC=gcc-4.9 CXX=g++-4.9 python setup.py build_ext
  - pip install .
  - pip install mock==3.0.*
  - pip install sphinx==1.7.5
  - pip install sphinx_rtd_theme==0.4.*
  - pip install  shuffle_graph>=2.1.0 similarity-index-of-label-graph>=2.0.1 ASLPAw>=2.1.0
  - pip install -r requirements.txt
  - pip install -r requirements_optional.txt

script:
  - py.test --cov=./ --cov-config=.coveragerc

after_success:
  - coveralls
