name: cdlib
dependencies:
- python>=3.8
- numpy
- matplotlib
- scikit-learn
- tqdm
- networkx==2.6.2
- demon
- python-louvain
- nf1
- scipy==1.6.2
- pulp
- seaborn==0.11.2
- pandas
- eva_lcd
- bimlpa
- markov_clustering
- chinese_whispers
- python-igraph
- angel_cd
- pooch
- dynetx
- thresholdclustering
- pyclustering
- python-Levenshtein
- graph-tool==2.44
