name: cdlib
dependencies:
- python=3.9
#- graph-tool # ==2.44
- numpy
- matplotlib
- scikit-learn
- tqdm
- networkx
- demon
- python-louvain
- nf1
- scipy
- pulp
- seaborn
- pandas
- eva_lcd
- bimlpa
- markov_clustering
# - chinese_whispers
- python-igraph
- angel_cd
- pooch
- dynetx
- thresholdclustering
#- pyclustering
- python-Levenshtein
