name: cdlib
dependencies:
- python>=3.8
- numpy
- future
- matplotlib
- scikit-learn
- tqdm
- networkx
- demon
- python-louvain
- nf1
- scipy
- omega_index_py3
- pulp
- seaborn
- pandas
- eva_lcd
- karateclub
- bimlpa
- markov_clustering
- chinese_whispers
- python-igraph
- leidenalg
- angel_cd
- pooch
- dynetx
- python-infomap>
- wurlitzer
- thresholdclustering
- pyclustering
- cython
- python-Levenshtein
- graph-tool
