{% set data = load_setup_py_data() %}

package:
  name: "cdlib"
  version: {{ data.get('version') }}

source:
  git_rev: {{ data.get('version') }}
  git_url: https://github.com/GiulioRossetti/cdlib

requirements:
  channels:
    - conda-forge
    - giuliorossetti
    - defaults
  host:
    - python
    - setuptools
  build:
    - python
    - setuptools
  run:
    - python>=3.8
    - numpy
    - future
    - matplotlib
    - scikit-learn
    - tqdm
    - networkx
    - demon
    - python-louvain
    - nf1
    - scipy
    - pulp
    - seaborn
    - pandas
    - eva_lcd
    - karateclub
    - bimlpa
    - markov_clustering
    - chinese_whispers
    - python-igraph
    - leidenalg
    - angel_cd
    - pooch
    - dynetx
    - python-infomap>
    - wurlitzer
    - thresholdclustering
    - pyclustering
    - cython
    - python-Levenshtein
    - graph-tool

about:
  home: https://github.com/GiulioRossetti/cdlib
  license: BSD-2-Clause
  license_familY: BSD
  license_file: LICENSE
  summary: "Community Discovery Library"

extra:
  recipe-maintainers:
    - GiulioRossetti
