{% set name = "cdlib" %}
{% set version = "0.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

requirements:
  host:
    - python==3.9
    - angel_cd
    - bimlpa
    - demon
    - dynetx
    - eva_lcd
    - leidenalg
    - markov_clustering
    - matplotlib
    - networkx>=3.0
    - nf1
    - numpy
    - pandas
    - pip
    - pooch
    - pulp
    - python-igraph
    - python-levenshtein
    - python-louvain
    - scikit-learn
    - scipy
    - seaborn
    - thresholdclustering
    - tqdm
    - setuptools
  build:
    - python
    - setuptools
  run:
    - angel_cd
    - bimlpa
    - demon
    - dynetx
    - eva_lcd
    - markov_clustering
    - matplotlib
    - networkx>3.0
    - nf1
    - numpy
    - pandas
    - pooch
    - pulp
    - python-igraph
    - python-levenshtein
    - python-louvain
    - scikit-learn
    - scipy
    - seaborn
    - thresholdclustering
    - tqdm

about:
  home: "https://github.com/GiulioRossetti/cdlib"
  license: "BSD"
  license_family: "BSD"
  license_file: ""
  summary: "Community Discovery Library"
  doc_url: "https://cdlib.readthedocs.io/"
  dev_url: "https://github.com/GiulioRossetti/cdlib"

extra:
  recipe-maintainers:
    - GiulioRossetti
