{% set name = "bimlpa" %}
{% set version = "0.1.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "b49b4b3010416d824b9b0f561e5a8afae41dd1692503113fd9c46eb8cf86dda5"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - matplotlib
    - networkx
    - pip
    - python
    - scikit-learn
  run:
    - matplotlib
    - networkx
    - python
    - scikit-learn

test:
  imports:
    - BiMLPA

about:
  home: "https://github.com/hbkt/BiMLPA"
  license: "BSD"
  license_family: "BSD"
  license_file: ""
  summary: "Community detection in bipartite networks using multi-label propagation algorithm"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - your-github-id-here
