{% set name = "aslpaw" %}
{% set version = "2.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/fsssosei/ASLPAw

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - count-dict >=1.0.3
    - multivalued-dict >=1.7.3
    - networkx >=2.4
    - pip
    - python
    - scikit-learn >=0.21.3
    - shuffle-graph >=1.1.2
  run:
    - count-dict >=1.0.3
    - multivalued-dict >=1.7.3
    - networkx >=2.4
    - python
    - scikit-learn >=0.21.3
    - shuffle-graph >=1.1.2

test:
  imports:
    - ASLPAw_package

about:
  home: "https://github.com/fsssosei/ASLPAw"
  license: "GNU Affero General Public v3"
  license_family: "AGPL"
  license_file: ""
  summary: "Adaptive overlapping community discovery algorithm package in python."
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - your-github-id-here
